name: Daily Green City Index Update
on:
  schedule:
    # Runs at 2:00 UTC every day
    - cron: '0 2 * * *'  # Corrected syntax (minutes, hours, day, month, day of week)
  workflow_dispatch:  # Allows manual triggering
jobs:
  update-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          
      - name: Run daily update with logging
        run: |
          echo "Running GCI pipeline..."
          python -m backend.pipeline.run_daily_update
          echo "Exit code: $?"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
      
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/
          git diff --quiet && git diff --staged --quiet || git commit -m "Daily GCI update $(date +'%Y-%m-%d')"
          git push
          
      - name: Archive logs
        if: always()  # Run even if previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: update-logs
          path: logs/
